#!/bin/bash
workdir=$(pwd)
sudo kill -9 $(pgrep experiment.sh) 
sudo kill -9 $(pgrep node) 
sudo kill -9 $(pgrep runAleth.sh) 
sudo kill -9 $(pgrep aleth) 
(cd ../AlethWithTraceRecorder/bootstrap-scripts/aleth-ethereum && ./runAleth.sh cslliuye > aleth.log 2>&1 &)
sleep 20
(cd $workdir && ./experiment.sh cslliuye > experiment.log > experiment.log 2>&1 &)
