<template>
  <b-container fluid>
    <b-row>
      <b-col align-v="center" cols="5" md="3">
        <b-form-textarea id="textarea" v-model="text" placeholder="Write your state machine..." rows="42" max-rows="42"
          @change="OnStateMachineChange"></b-form-textarea>
        <span> {{text}}</span>
      </b-col>
      <b-col align-v="center" cols="5" md="7">
        <b-row>

              <div class="container" style="width: 100%"  v-html="lSVGInAString">
                   <!-- <canvas id="canvas">
                   </canvas> -->
                  <!-- <iframe  v-html="lSVGInAString"> 
                        Figure generated by state machine file lefthand
                  </iframe> -->
              </div>
         <!-- </b-container> -->
        </b-row>
        <b-row>
          <div class="container" style="width: 100%">
            <b-button class="mr-2" variant="primary">Upload model</b-button>
            <b-button class="ml-2" variant="primary">Test</b-button>
            <b-card class="mt-3" border-variant="success" header="Log Result" header-bg-variant="success"
              header-text-variant="white" body-border-variant="success" body-bg-variant="light" align="center">
              <b-card-text>{{log}}</b-card-text>
            </b-card>
          </div>
        </b-row>

      </b-col>
      <b-col align-v="center" cols="6" md="2">
        <b-form-textarea id="textarea" v-model="text" placeholder="Modify the model  testing script..." rows="42"
          max-rows="42"></b-form-textarea>
      </b-col>
    </b-row>
  </b-container>
</template>


<script>
//  import Canvg from 'canvg';
  export default {
    name: "ModelTest",
    data: function () {
      return {
        text: null,
        lSVGInAString: null,
        log: "<p>this is the place to show running log </p>" + this.$smcat
      };
    },
    methods: {
      OnStateMachineChange(e) {
        console.log(e); 
        try {
          const lSVGInAString = this.$smcat.render(
           this.text
           , {
              outputType: "svg",
              direction: "left-right",
            }
          );
          // console.log(lSVGInAString);
         var  parser = new DOMParser();
          var xmlDoc = parser.parseFromString(lSVGInAString, "text/xml");
          console.log(xmlDoc);
          xmlDoc.getElementsByTagName("svg")[0].setAttribute("width", "100%");
          var s = new XMLSerializer();
          this.lSVGInAString= s.serializeToString(xmlDoc);
 
          // this.lSVGInAString = lSVGInAString;
          // var v = Canvg.fromString(ctx,lSVGInAString );
          // v.resize(800, 800, 'xMidYMid meet');
      // Start SVG rendering with animations and mouse handling.
            // v.start();

        } catch (pError) {
          console.error(pError);
        }
      }
    },
    computed: {

    },
    props: {
      msg: String
    }
  };
</script>

<style scoped lang="scss">
  .container /deep/ {
    @import "~bootstrap-vue/dist/bootstrap-vue";
    @import "~bootstrap/dist/css/bootstrap";
  }
</style>