<template>
<b-container  fluid  >
<b-row>
    <b-col align-v="center" cols="5" md="3" >   
       <b-form-textarea
      id="textarea"
      v-model="text"
      placeholder="Write your state machine..."
      rows="42"
      max-rows="42"
    ></b-form-textarea>
    </b-col>
     <b-col align-v="center" cols="5" md="4" class ="bg-primary">   
       <b-row >
            <div id="d1" class="col-xs-5 col-md-4" style="height:400px;">
                Figure generated by state machine file lefthand
            </div>
       </b-row>
       <b-row class ="bg-danger">
         hello world
       </b-row>
    
    </b-col>
    <b-col align-v="center" cols="6" md="5"  class ="bg-danger">   
      hello world
       <b-card class="mt-3" header="Log Result">
            <span v-html="log"></span>
        </b-card>
    </b-col>
</b-row>
</b-container>
</template>


<script>
  export default {
    name: "ModelTest",
    data: function () {
      return {
        log: ""
      };
    },
    methods: {
      },
    props: {
      msg: String
    }
  };
</script>

<style scoped lang="scss">
  .container /deep/ {
    @import "~bootstrap-vue/dist/bootstrap-vue";
    @import "~bootstrap/dist/css/bootstrap";
  }
</style>